### ISSUE TITLE
mop.rsi with inhand-middle-fill-2 state

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#105]
![image](https://github.com/user-attachments/assets/312081c6-4c5e-4b78-b872-96a9c477b6e5)
![image](https://github.com/user-attachments/assets/512833eb-5348-495c-89b7-683b4742cba3)

**Comment by Rinary1** [comment]
at what point did you get this error?

**Comment by Rinary1** [comment]
![image](https://github.com/user-attachments/assets/7a4778eb-b0ec-4dc9-86d2-2f5b9c59640d)
![image](https://github.com/user-attachments/assets/1fafa5e7-9fec-41a2-8791-9fc564b6aa11)

it's on debug server

**Comment by fqqf** [comment]
i got it while playing. Jani has replaced his arm with mop
