### ISSUE TITLE
build and server lag like crazy

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#107]
![image](https://github.com/user-attachments/assets/3f027cff-6f66-4e65-8241-078437ed7d35)
Drops up to 20 fps for me on local build, and up to 10 on server
![image](https://github.com/user-attachments/assets/538b65ec-351c-486b-ab81-4975aaa5fc56)

**Comment by StarlightHost** [comment]
The server had issues last night due to the overloaded database, but I don't understand how that relates to the FPS at all.

**Comment by fqqf** [comment]
> The server had issues last night due to the overloaded database, but I don't understand how that relates to the FPS at all.


my apologies for not clarifying. I am asking is there a way to profile where performance issue happens? Because for me our local build lags much more then vanilla wizden one and i would like to fix it

**Comment by StarlightHost** [comment]
> > The server had issues last night due to the overloaded database, but I don't understand how that relates to the FPS at all.
> 
> my apologies for not clarifying. I am asking is there a way to profile where performance issue happens? Because for me our local build lags much more then vanilla wizden one and i would like to fix it


Well, then we need to use the standard sharp profiling options.
If it's Visual Studio, then use the Visual Studio profiler, if it's Rider, then DotTrace.

As far as I know, the client-side doesn't have the same metrics as the server-side.
And with all the prediction and infinite loops, there's chaos on the client even in the default build.

**Comment by fqqf** [comment]
i see, alright, thanks for clarifying i guess
