### ISSUE TITLE
sprite gets cut in character edit ui

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#110]
sometimes it just cuts sprite 
![image](https://github.com/user-attachments/assets/cc004116-6d71-440a-8237-170363dbdbaf)
![image](https://github.com/user-attachments/assets/06c66441-c3b6-4982-b765-ad24c2c52fa4)
but after resizing window it fixes itself
![image](https://github.com/user-attachments/assets/89f338a3-512e-44aa-9690-08d424ab2cde)

**Comment by Rinary1** [comment]
I can't get this bug with a completely clean build(just installed) in game. On debug builds, also no this problem, clean game content and engines
