### ISSUE TITLE
job console

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#115]
![image](https://github.com/user-attachments/assets/f381f263-6736-4b74-9345-ef70519bfd47)

**Comment by fqqf** [comment]
confirmed, got the same issue

**Comment by Rinary1** [comment]
if you add/remove on any id card access it lost his job icon, for recover it, you need use selector
![image](https://github.com/user-attachments/assets/785ee414-8c3a-4954-8ddb-e720fb86669c)
