### ISSUE TITLE
spider eggs inside every humanoid

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#116]
![image](https://github.com/user-attachments/assets/56d951ef-4790-4141-be00-8927254da145)

**Comment by Rinary1** [comment]
spider eggs it's a component on a entity, lol. It's don't bag
![image](https://github.com/user-attachments/assets/745ed3b9-5cc3-4bac-a83c-c1f007c846e8)
![image](https://github.com/user-attachments/assets/4d57551d-7d47-4909-8bc6-b6e6c189f674)
