### ISSUE TITLE
felionoid sunglasses sprite bug

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#142]
felionoid while wearing sunglasses sprite bug

![image](https://github.com/user-attachments/assets/98ce11e1-0008-4a0f-a97a-9128436751ae)

https://discord.com/channels/1272545509562777621/1315396312354787439/1315396312354787439

**Comment by Rinary1** [comment]
CLIENT SIDE DISPLACEMENT BUG, THIS NOT A SERVER BUG, CLEAR OLD SERVER CONTENT AND BUG WILL BE FIXED
