### ISSUE TITLE
[PROPOSAL] Legalizing stealth lings

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#157]
![image](https://github.com/user-attachments/assets/daa2f446-6693-43a5-89f8-4934c8d84760)
basically ling antag can just morph and solo no-damage any salv syndie exp

------
I don't really care about that, tbh i think it is a pretty smart move, but i suggest we make syndies attack anything that attacks them (except other syndies) , this way lings still can morph in monkey to decieve syndies and stealth loot, but once they attack at least one syndie, everyone will start being agressive to em

-------
And also its considered bag abusing amongst some admins, so yeah..
![image](https://github.com/user-attachments/assets/1e29236c-014b-41d3-985c-3dd579389edb)

**Comment by Rinary1** [comment]
fixed
