### ISSUE TITLE
magistrate black screen

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#172]
![image](https://github.com/user-attachments/assets/8742655c-3599-44ef-8bf6-fb22df4b4b7e)
Magistrate often spawns with black screen, this happens really often

![image](https://github.com/user-attachments/assets/e48dca71-9a05-41d7-bd0e-bae005145717)
![image](https://github.com/user-attachments/assets/72fc32c0-2ea1-452f-ba6b-b83913c19f95)
![image](https://github.com/user-attachments/assets/ce0a7753-35ea-4fb6-a84f-9501e76f670c)

Similar bug happens at other roles as well (see #176) but magistrate's been getting this literally almost every round

**Comment by fqqf** [comment]
![image](https://github.com/user-attachments/assets/cbf73607-93e3-4abf-923e-cd757905924e)

**Comment by fqqf** [comment]
https://discord.com/channels/1272545509562777621/1319146217707536394/1319146217707536394

**Comment by Rinary1** [comment]
fixed
