### ISSUE TITLE
Rule 13 labeled as rule 11

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#174]
![image](https://github.com/user-attachments/assets/894bfb5b-6df6-4cda-81a7-08eb2b8b3559)

in addition, when clicking on 13.1, 13.2 or 13.3 they are also incorrectly labeled as 11.1, 11.2, and 11.3 respectively 

https://discord.com/channels/1272545509562777621/1319055889738764368/1319055889738764368

**Comment by Rinary1** [comment]
fixed
