### ISSUE TITLE
state electrified does not exist in set rsi

### ISSUE THREAD

**Issue by fqqf** [ss14Starlight/space-station-14#181]
![image](https://github.com/user-attachments/assets/01fadd3e-8bfd-42dc-8062-f19f369c0c82)

**Comment by fqqf** [comment]
![image](https://github.com/user-attachments/assets/9f2212d9-9fa9-472c-aaba-1ae5047c7717)
same for engineering.rsi

**Comment by fqqf** [comment]
same for hydroponics.rsi
![image](https://github.com/user-attachments/assets/0f678415-08a6-4d07-8c5d-7ef92967e7d7)

**Comment by fqqf** [comment]
same for maint.rsi and medical.rsi

**Comment by fqqf** [comment]
basically all glass airlocks, freezer.rsi, etc..

**Comment by Rinary1** [comment]
![image](https://github.com/user-attachments/assets/5262c6e9-ef3a-4532-8e3a-5f3f429989b5)

**Comment by Rinary1** [comment]
![image](https://github.com/user-attachments/assets/dcdd86ac-7e55-4dc3-afc7-e6071c8c1bd8)

**Comment by Rinary1** [comment]
at release and debug, this problem resolved
