### ISSUE TITLE
Starlight license feedback

### ISSUE THREAD

**Issue by TsjipTsjip** [ss14Starlight/space-station-14#82]
I've recently heard about the starlight project, and decided to have a look. I was excited to see a custom license being used, as it shows a clear commitment of the team to care about the project and curate it, however the license text itself is poorly constructed and has multiple issues.

## Listing some of the issues

**Application domain:** The language used to define the application domain (`... applies exclusively to the code derived from the Starlight project (the "Fork").`) is crude and poorly defined, due to the fact that "the Starlight project" and "the Fork" are not defined prior. This leaves this clause open to interpretation, and does not provide sufficient clarity on when and where the license applies.

It's hard to fully address this, as it is a problem inherent to writing your own license, and it is also the reason why writing a custom license rather than using an industry-standard license is generally discouraged. Industry-standard licenses are internationally well-understood. Custom licenses do not have this recognition and therefore must not leave any room for interpretation.

Using a custom license also introduces a lot of friction. As a fork developer of another fork, starlight is ineligible in its current state to be used at all for sourcing features to us, as I do not want to run the risk of getting that interpretation wrong.

**Missing permissions:** The MIT license grants a lot of permissions (use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software), the Starlight license grants only two. Under the current license, it could be argued that creating a fork of the repository is a license violation, as the copy permission is not explicitly granted. One could also argue it is implicit in the "use" definition, but that's again a case of lack of clarity.

A more problematic case is the case of redistribution. Presently, you are not giving an explicit permission to redistribute the code or derivatives (i.e. via public repositories, Robust.Cdn instances, ...), which has consequences for anyone intending to use the fork at all.

**Attribution clause:** What does this mean? A software license applies to the code and derivatives of the code (binaries, ...) alone. This clauses mentions discord servers and other social media. What is the intention behind this? It is absolutely unfounded to seek action based on someone posting a screenshot from the game based on a software license for example. I feel as if this clause is missing its original purpose, but I cannot discern what that purpose might be so maybe I am wrong.

This clause should at least clearly define the following:
- What attribution is, for the purposes of the project. (Feels like this is entirely covered by clause 2 as well.)
- A specification of "any mention", because this is unnecessarily broad.

**Code contribution restriction:** The github PR template includes a check that states `- [ ] My changes are not licensed in any way.`. People who check this box explicitly affirm that their contribution is not licensed to **any** software license, including the starlight license. Additionally, checking this box makes this affirmation for the contribution **in that PR only**, as such they are free to open pull requests to other repositories containing the same contribution, as they are the owner of the code, without requirement to notify you of this fact.

I believe it is likely that this checkbox is entirely missing its intention, that being "I am contributing this code to the ss14Starlight/space-station-14 repository under the permissions and restrictions imposed by the Starlight license.". Even then, a code owner is still free entirely to contribute the same change to other repositories as they own the code. You cannot take ownership of code as a repository, unless you additionally require your contributors to expressly waive code ownership.

**Exemption by permission clause:** This clause uses the term "this rule" to define an exception, which under a reasonable interpretation would mean the entire section 3 under conditions of the license. Using the wording "This rule does not apply ..." means, under those conditions mentioned, the entire rule essentially does not exist in the license. This means the linking requirement (condition 2) and the attribution requirement (condition 1) still apply to those conditions, as they are mentioned in separate rules.

Additionally, this clause also uses the term "the official project", which is unclear. Additionally, any code contributed to this project should (in theory) automatically comply with the license, so an explicit exemption for yourself is unnecessary.

**Excluded commits:** Good! This is actually 100% solid, though it would be preferable to make them into links to reduce developer friction.

**Lack of links in general:** The "Starlight project" is poorly defined, and adding links to explicitly mention the repository and other identifying marks would greatly help in further clarifying this license. 

## Concluding

The Starlight license strikes me as a license that is based on the MIT license in purpose, but by the language used does a totally different thing. It would very much help to clarify the purpose of what one is trying to achieve here. The custom license as-is introduces a lot of friction for me as a developer to want to interact and contribute to the repositories, due to the uncertainties that it introduces to my code.

I would love to discuss this further on discord and provide additional feedback if it is decided things must be changed. If it is decided to ignore this feedback, that is fine by me as well. This is a motivated opinion, after all. What needs to be clearly understood however is that a software license is a legal document where using natural language sadly will detract from the effectiveness of the license.

**Comment by Rinary1** [comment]
Oh. I didn't think be so picky about a license that's really just a formality. But, yeah, it's worth change it

**Comment by Rinary1** [comment]
@TsjipTsjip I've edited the license, hopefully now it's clearer and covers all the problems described here.
