### ISSUE TITLE
Issue labeler is failing

### ISSUE THREAD

**Issue by TsjipTsjip** [ss14Starlight/space-station-14#83]
## Description

Issue creation labeler is failing. The error points towards a permissions issue. Did you give GitHub actions permission to modify issues and PR's?

**Reproduction**

1. Create any issue.

**Media**

Overview of failed runs: https://github.com/ss14Starlight/space-station-14/actions/workflows/labeler-untriaged.yml

**Comment by Rinary1** [comment]
Fixed https://github.com/ss14Starlight/space-station-14/commit/681fa2b3612b97c78d39d129ac2d25dfcc5d7a2e
